# Generated by Django 4.2.9 on 2024-04-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_partnerslogomodel_subsidiarieslogomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandsLogoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Сюда загружайте логотип для бренда и одну', upload_to='brands_logos', verbose_name='brands_logo')),
                ('link', models.TextField(blank=True, help_text='Сюда вы должны поставить ссылку на сайт бренда или т.д НО НЕ Обязательно!', null=True, verbose_name='brands_link')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Brand_logo',
                'verbose_name_plural': 'Brands_logos',
            },
        ),
    ]
