# Generated by Django 5.0.1 on 2024-01-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Сюда надо писать названия категории например:РАСТИТЕЛЬНОЕ МАСЛО и т.д', max_length=90, verbose_name='title')),
                ('description', models.TextField(help_text='Описания для вашего категории', verbose_name='cat_description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
