# Generated by Django 5.0.1 on 2024-02-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_categoryimagesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Сюда надо писать название товара например:Кубанское золото..', max_length=120, verbose_name='product_title')),
                ('short_descriptions', models.TextField(help_text='Сюда надо писать краткое описания для вашего товара', verbose_name='product_short_description')),
                ('descriptions', models.TextField(help_text='Сюда надо писать описания для вашего товара', verbose_name='product_description')),
                ('term', models.CharField(help_text='Сюда надо писать срок например: 12 месяцев...', max_length=50, verbose_name='product_term')),
                ('GMO', models.CharField(help_text='Сюда надо писать с ГМО или БЕЗ ГМО', max_length=30, verbose_name='product_GMO')),
                ('substance', models.CharField(help_text='Сюда надо писать вещество например: Без холестерина....', max_length=40, verbose_name='product_substance')),
                ('object3D', models.FileField(help_text='Сюда надо загрузить 3D обьект', upload_to='objects3D', verbose_name='product_object3D')),
                ('image', models.FileField(help_text='Сюда надо загрузить изображения товара', upload_to='image', verbose_name='product_image')),
                ('volume', models.CharField(help_text='Сюда надо указывать обьем в литрах', max_length=50, verbose_name='product_volume')),
                ('count', models.PositiveIntegerField(default=1, help_text='По умолчанию тут стоит 1 если необходимо можете менять', verbose_name='product_count')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
