# Generated by Django 5.0.1 on 2024-02-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='GMO_en',
            field=models.CharField(help_text='Сюда надо писать с ГМО или БЕЗ ГМО', max_length=30, null=True, verbose_name='product_GMO'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='GMO_ru',
            field=models.CharField(help_text='Сюда надо писать с ГМО или БЕЗ ГМО', max_length=30, null=True, verbose_name='product_GMO'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='GMO_uz',
            field=models.CharField(help_text='Сюда надо писать с ГМО или БЕЗ ГМО', max_length=30, null=True, verbose_name='product_GMO'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='descriptions_en',
            field=models.TextField(help_text='Сюда надо писать описания для вашего товара', null=True, verbose_name='product_description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='descriptions_ru',
            field=models.TextField(help_text='Сюда надо писать описания для вашего товара', null=True, verbose_name='product_description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='descriptions_uz',
            field=models.TextField(help_text='Сюда надо писать описания для вашего товара', null=True, verbose_name='product_description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_descriptions_en',
            field=models.TextField(help_text='Сюда надо писать краткое описания для вашего товара', null=True, verbose_name='product_short_description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_descriptions_ru',
            field=models.TextField(help_text='Сюда надо писать краткое описания для вашего товара', null=True, verbose_name='product_short_description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_descriptions_uz',
            field=models.TextField(help_text='Сюда надо писать краткое описания для вашего товара', null=True, verbose_name='product_short_description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='substance_en',
            field=models.CharField(help_text='Сюда надо писать вещество например: Без холестерина....', max_length=40, null=True, verbose_name='product_substance'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='substance_ru',
            field=models.CharField(help_text='Сюда надо писать вещество например: Без холестерина....', max_length=40, null=True, verbose_name='product_substance'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='substance_uz',
            field=models.CharField(help_text='Сюда надо писать вещество например: Без холестерина....', max_length=40, null=True, verbose_name='product_substance'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='term_en',
            field=models.CharField(help_text='Сюда надо писать срок например: 12 месяцев...', max_length=50, null=True, verbose_name='product_term'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='term_ru',
            field=models.CharField(help_text='Сюда надо писать срок например: 12 месяцев...', max_length=50, null=True, verbose_name='product_term'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='term_uz',
            field=models.CharField(help_text='Сюда надо писать срок например: 12 месяцев...', max_length=50, null=True, verbose_name='product_term'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_en',
            field=models.CharField(help_text='Сюда надо писать название товара например:Кубанское золото..', max_length=120, null=True, verbose_name='product_title'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_ru',
            field=models.CharField(help_text='Сюда надо писать название товара например:Кубанское золото..', max_length=120, null=True, verbose_name='product_title'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_uz',
            field=models.CharField(help_text='Сюда надо писать название товара например:Кубанское золото..', max_length=120, null=True, verbose_name='product_title'),
        ),
    ]
