# Generated by Django 5.0.1 on 2024-02-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_categorymodel_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(help_text='Тут можете выбрать категории для вашего продукта', related_name='pr_categories', to='product.categorymodel'),
        ),
    ]
