# Generated by Django 4.2.9 on 2024-02-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_categorymodel_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='objectPDF',
            field=models.FileField(help_text='Сюда надо загрузить PDF если необходимо!', null=True, upload_to='product_files', verbose_name='object_pdf'),
        ),
    ]
