# Generated by Django 4.2.9 on 2024-04-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productmodel_objectpdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImagesModel',
        ),
    ]
