# Generated by Django 4.2.9 on 2024-04-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_delete_categoryimagesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='object3D',
        ),
    ]
