# Generated by Django 4.2.9 on 2024-04-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_productmodel_object3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Тут можете выбрать категории для вашего продукта', related_name='pr_categories', to='product.categorymodel'),
        ),
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Сюда надо писать названия подкатегории например:РАСТИТЕЛЬНОЕ МАСЛО и т.д', max_length=90, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Описания для вашего подкатегории (Не обьязательно)', null=True, verbose_name='cat_description')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('category', models.ForeignKey(help_text='Сюда надо указать категорию', on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='product.categorymodel')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Тут можете выбрать подкатегорию для вашего продукта', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_subcategories', to='product.subcategorymodel'),
        ),
    ]
