# Generated by Django 4.2.9 on 2024-04-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productmodel_category_subcategorymodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategorymodel',
            old_name='title',
            new_name='subcategory',
        ),
    ]
