# Generated by Django 4.2.9 on 2024-04-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_title_subcategorymodel_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['pk'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
