# Generated by Django 4.2.9 on 2024-04-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['my_order'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
