# Generated by Django 4.2.9 on 2024-04-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productmodel_options_productmodel_my_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
