# Generated by Django 4.2.9 on 2024-04-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_productmodel_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='order',
        ),
    ]
