# Generated by Django 4.2.9 on 2024-04-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='my_order'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='my_order'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='my_order'),
        ),
    ]
