# Generated by Django 4.2.9 on 2024-04-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_categorymodel_my_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='description_en',
            field=models.TextField(blank=True, help_text='Описания для вашего подкатегории (Не обьязательно)', null=True, verbose_name='cat_description'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Описания для вашего подкатегории (Не обьязательно)', null=True, verbose_name='cat_description'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='description_uz',
            field=models.TextField(blank=True, help_text='Описания для вашего подкатегории (Не обьязательно)', null=True, verbose_name='cat_description'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='subcategory_en',
            field=models.CharField(help_text='Сюда надо писать названия подкатегории например:РАСТИТЕЛЬНОЕ МАСЛО и т.д', max_length=90, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='subcategory_ru',
            field=models.CharField(help_text='Сюда надо писать названия подкатегории например:РАСТИТЕЛЬНОЕ МАСЛО и т.д', max_length=90, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='subcategory_uz',
            field=models.CharField(help_text='Сюда надо писать названия подкатегории например:РАСТИТЕЛЬНОЕ МАСЛО и т.д', max_length=90, null=True, verbose_name='title'),
        ),
    ]
