# Generated by Django 4.2.9 on 2024-05-18 21:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_subcategorymodel_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='GMO',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='GMO_en',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='GMO_ru',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='GMO_uz',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='count',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='substance',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='substance_en',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='substance_ru',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='substance_uz',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='term',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='term_en',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='term_ru',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='term_uz',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='volume',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='descriptions',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Сюда надо писать описания для вашего товара', verbose_name='product_description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='descriptions_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Сюда надо писать описания для вашего товара', null=True, verbose_name='product_description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='descriptions_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Сюда надо писать описания для вашего товара', null=True, verbose_name='product_description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='descriptions_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Сюда надо писать описания для вашего товара', null=True, verbose_name='product_description'),
        ),
    ]
