# Generated by Django 5.0.1 on 2024-02-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Тут должны писать название вакансии например:Финансист...', max_length=90, verbose_name='vacancy_title')),
                ('description', models.TextField(help_text='Тут должны писать описание(характеристики) вашего вакансии', verbose_name='vacancy_description')),
                ('image', models.FileField(upload_to='vacancy_images')),
                ('start_time', models.DurationField(help_text='Начало работы например 9:00', verbose_name='Начало работы')),
                ('end_time', models.DurationField(help_text='Окончание работы например 18:00', verbose_name='Окончание работы')),
                ('price', models.IntegerField(help_text='Тут указываете ЗП', verbose_name='vacancy_price')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancy',
            },
        ),
    ]
