# Generated by Django 5.0.1 on 2024-02-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancymodel',
            name='end_time',
            field=models.DurationField(default='19:00', help_text='Окончание работы например 18:00', verbose_name='Окончание работы'),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='start_time',
            field=models.DurationField(default='09:00', help_text='Начало работы например 9:00', verbose_name='Начало работы'),
        ),
    ]
