# Generated by Django 5.0.1 on 2024-02-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_alter_vacancymodel_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancymodel',
            name='price',
            field=models.FloatField(help_text='Тут указываете ЗП', verbose_name='vacancy_price'),
        ),
    ]
