# Generated by Django 5.0.1 on 2024-02-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_vacancymodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancymodel',
            name='end_time',
            field=models.CharField(default='19:00', help_text='Окончание работы например 18:00', max_length=30, verbose_name='Окончание работы'),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='start_time',
            field=models.CharField(default='09:00', help_text='Начало работы например 9:00', max_length=30, verbose_name='Начало работы'),
        ),
    ]
