# Generated by Django 5.0.1 on 2024-02-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_alter_vacancymodel_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancymodel',
            name='description_en',
            field=models.TextField(help_text='Тут должны писать описание(характеристики) вашего вакансии', null=True, verbose_name='vacancy_description'),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='description_ru',
            field=models.TextField(help_text='Тут должны писать описание(характеристики) вашего вакансии', null=True, verbose_name='vacancy_description'),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='description_uz',
            field=models.TextField(help_text='Тут должны писать описание(характеристики) вашего вакансии', null=True, verbose_name='vacancy_description'),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='title_en',
            field=models.CharField(help_text='Тут должны писать название вакансии например:Финансист...', max_length=90, null=True, verbose_name='vacancy_title'),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='title_ru',
            field=models.CharField(help_text='Тут должны писать название вакансии например:Финансист...', max_length=90, null=True, verbose_name='vacancy_title'),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='title_uz',
            field=models.CharField(help_text='Тут должны писать название вакансии например:Финансист...', max_length=90, null=True, verbose_name='vacancy_title'),
        ),
    ]
