# Generated by Django 4.2.9 on 2024-05-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_vacancymodel_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancymodel',
            name='price',
        ),
    ]
